site_name: Coronium Core
pages:
  - 'Introduction': 'index.md'
  - 'Server Install':
    - 'DigitalOcean': 'server-install/digitalocean.md'
    - 'Amazon EC2': 'server-install/ec2.md'
    - 'Post Install': 'server-install/postinstall.md'
  - 'Server Setup': 'server-setup/index.md'
  - 'Server Guide': 'server-guide/index.md'
  - 'Server API':
    - 'Overview': 'server-api/overview.md'
    - 'API': 'server-api/api-api.md'
    - 'Crypto': 'server-api/crypto-api.md'  
    - 'DB': 'server-api/db-api.md'
    - 'GeoIP': 'server-api/geoip-api.md'
    - 'JSON': 'server-api/json-api.md'
    - 'Lpeg': 'server-api/lpeg-api.md'
    - 'MySQL': 'server-api/mysql-api.md'
    - 'Network': 'server-api/network-api.md'
    - 'Utils': 'server-api/utils-api.md'
  - 'Client Setup': 'client-setup/index.md'
  - 'Client Guide': 'client-guide/index.md'
  - 'Client API':
    - 'API': 'client-api/api-api.md'
    - 'Core': 'client-api/core-api.md'
    - 'Files': 'client-api/files-api.md'
  - 'Plugins API':
    - 'Users': 'plugins-api/users-api.md'
  - 'Examples': 'example.md'
  - 'HTTPS / SSL': 'ssl.md'
  - 'About': 'about.md'
copyright: "&copy;2017 C. Byerley - develephant.com"
theme: readthedocs
site_url: https://develephant.github.io/coronium-core-docs
site_dir: ../docs
markdown_extensions:
  - admonition
  - codehilite