site_name: Coronium Core
pages:
  - 'Introduction': 'index.md'
  - 'Server Install':
    - 'DigitalOcean': 'server-install/digitalocean.md'
    - 'Amazon EC2': 'server-install/ec2.md'
    - 'Post Install': 'server-install/postinstall.md'
  - 'Server Guide': 'server-guide/index.md'
  - 'Server Modules':
    - 'API': 'server-modules/api.md' 
    - 'Data': 'server-modules/data.md'
    - 'Files': 'server-modules/files.md'
    - 'Mongo': 'server-modules/mongo.md'
    - 'MySQL': 'server-modules/mysql.md'
    - 'Network': 'server-modules/network.md'
    - 'Utils': 'server-modules/utils.md'
  - 'Client Guide': 'client-guide/index.md'
  - 'Client Module':
    - 'API': 'client-module/api.md'
    - 'Core': 'client-module/core.md'
    - 'Data': 'client-module/data.md'
    - 'Email': 'client-module/email.md'
    - 'Files': 'client-module/files.md'
    - 'MySQL': 'client-module/mysql.md'
  - 'Pages Guide':
    - 'Pages API': 'pages-guide/api.md'
    - 'Usage': 'pages-guide/usage.md'
    - 'Templates': 'pages-guide/templates.md'
    - 'Configuration': 'pages-guide/config.md'
  - 'HTTPS / SSL': 'ssl.md'
  - 'Version Updates': 'updates.md'
  - 'Demo Project': 'demo.md'
  - 'Video Tutorials': 'screencasts.md'
  - 'About': 'about.md'
copyright: "&copy;2017 C. Byerley ( develephant )"
theme: material
site_url: https://develephant.github.io/coronium-core-docs
site_favicon: 'imgs/favicon.ico'
site_dir: ../docs
extra:
  logo: 'imgs/rnd-dev.png'
  social:
    - type: 'support'
      link: 'https://forums.coronalabs.com/forum/643-coronium/'
    - type: 'twitter'
      link: 'https://twitter.com/develephant'
    - type: 'globe'
      link: 'http://develephant.com'
  palette:
    primary: 'blue-grey'
    accent: 'teal'
markdown_extensions:
  - admonition
  - codehilite