site_name: Coronium Core
pages:
  - 'Introduction': 'index.md'
  - 'Core Server':
    - 'Installation':
      - 'DigitalOcean': 'server/installation/digitalocean.md'
      - 'Amazon EC2': 'server/installation/amazon.md'
      - 'Post Install': 'server/installation/postinstall.md'
    - 'Webmin':
      - 'Browser Access': 'server/webmin/setup.md'
      - 'Application Scope': 'server/webmin/scope.md'
      - 'Mailgun Config': 'server/webmin/mailgun.md'
      - 'Password': 'server/webmin/password.md'
    - 'Guide': 
      - 'Logging In': 'server/guide/login.md'
      - 'Server Key': 'server/guide/key.md'
      - 'General Usage': 'server/guide/usage.md'
      - 'HTTPS/SSL': 'server/guide/ssl.md'
      - 'MySQL Server': 'server/guide/mysql.md'
    - 'Modules':
      - 'API': 'server/modules/api.md' 
      - 'Data': 'server/modules/data.md'
      - 'Email': 'server/modules/email.md'
      - 'Files': 'server/modules/files.md'
      - 'Mongo': 'server/modules/mongo.md'
      - 'MySQL': 'server/modules/mysql.md'
      - 'Network': 'server/modules/network.md'
      - 'Pages':
        - 'Pages API': 'server/modules/pages/api.md'
        - 'Usage': 'server/modules/pages/usage.md'
        - 'Templates': 'server/modules/pages/templates.md'
        - 'Configuration': 'server/modules/pages/config.md'        
      - 'Template': 'server/modules/template.md'
      - 'Utils': 'server/modules/utils.md'
    - 'Updates': 'server/updates.md'  
  - 'Core Client':
      - 'Usage': 'client/guide/index.md'
      - 'Modules':
        - 'Analytics': 'client/modules/analytics.md'
        - 'API': 'client/modules/api.md'
        - 'Core': 'client/modules/core.md'
        - 'Data': 'client/modules/data.md'
        - 'Email': 'client/modules/email.md'
        - 'Files': 'client/modules/files.md'
        - 'MySQL': 'client/modules/mysql.md'
        - 'Users': 
          - 'Users API': 'client/modules/users/api.md'
          - 'Creating': 'client/modules/users/creating.md'
          - 'Updating': 'client/modules/users/updating.md'
          - 'Logging In': 'client/modules/users/login.md'
          - 'Confirmation': 'client/modules/users/confirmation.md'
      - 'Status Codes': 'client/codes.md'
  - 'Demo Project': 'demo.md'
  - 'Screencasts': 'screencasts.md'
  - 'About': 'about.md'
copyright: "&copy;2018 C. Byerley (develephant) | v2.3.1"
theme: material
site_url: https://develephant.github.io/coronium-core-docs
site_favicon: 'imgs/favicon.ico'
site_dir: ../docs
extra:
  logo: 'imgs/rnd-dev.png'
  social:
    - type: 'support'
      link: 'https://forums.coronalabs.com/forum/643-coronium/'
    - type: 'twitter'
      link: 'https://twitter.com/develephant'
    - type: 'globe'
      link: 'http://develephant.com'
  palette:
    primary: 'blue-grey'
    accent: 'teal'
markdown_extensions:
  - admonition
  - codehilite