site_name: Coronium Core
pages:
  - 'Introduction': 'index.md'
  - 'Server Install':
    - 'DigitalOcean': 'server-install/digitalocean.md'
    - 'Amazon EC2': 'server-install/ec2.md'
    - 'Post Install': 'server-install/postinstall.md'
  - 'Server Setup': 'server-setup/index.md'
  - 'Server Guide': 'server-guide/index.md'
  - 'Server API':
    - 'Overview': 'server-api/overview.md'
    - 'API': 'server-api/api.md' 
    - 'Data': 'server-api/data.md'
    - 'GeoIP': 'server-api/geoip.md'
    - 'JSON': 'server-api/json.md'
    - 'Mongo': 'server-api/mongo.md'
    - 'MySQL': 'server-api/mysql.md'
    - 'Network': 'server-api/network.md'
    - 'Utils': 'server-api/utils.md'
  - 'Client Setup': 'client-setup/index.md'
  - 'Client Guide': 'client-guide/index.md'
  - 'Client API':
    - 'API': 'client-api/api.md'
    - 'Core': 'client-api/core.md'
    - 'Files': 'client-api/files.md'
  - 'Examples': 'example.md'
  - 'HTTPS / SSL': 'ssl.md'
  - 'About': 'about.md'
copyright: "&copy;2017 C. Byerley - develephant.com"
theme: readthedocs
site_url: https://develephant.github.io/coronium-core-docs
site_dir: ../docs
markdown_extensions:
  - admonition
  - codehilite